#!groovy

// Generated by IBM TransformationAdvisor
// Thu Feb 28 05:43:12 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}