#!groovy

// Generated by IBM TransformationAdvisor
// Thu Feb 28 06:00:16 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'retailtrader'
    mvnCommands = '--version'
    test='false'
}